"""T09.1 legacy step 9.D: handle-bound existing/create path authorization.

``PathGuard`` authorizes an existing object (REPLACE semantics) or a
CREATE parent only when every fact family matches: canonical lexical paths
(Task 4.D), handle-derived final-object/root facts (Task 9.A observation
port), sealed Git/ignore facts (Task 9.C), sensitive-path rules and
protected-artifact rules (SPEC §1.4.2–1.4.3), and the frozen
``EditablePathPolicyV1`` (Task 6.A).  Every failure returns a closed
REJECTED handle with a stable error code and never falls back to string
authorization, never mutates the workspace, and never widens editable
policy.

This module also owns the shared path-fact tables consumed by the Git
preflight (9.C): the sensitive-path rules, the protected-artifact rules,
and the sealed gitignore rule vocabulary — one frozen source for both
consumers, imported one-directionally by ``git_preflight``.
"""

from __future__ import annotations

import fnmatch
import hashlib
import os
import re
from dataclasses import dataclass, field
from typing import Callable, Final, Literal, Protocol

from pydantic import (
    BaseModel,
    ConfigDict,
    StrictBool,
    StrictStr,
    field_validator,
    model_validator,
)

from src.vespercode.canonical.path_v1 import CanonicalRelativePathV1
from src.vespercode.profiles.reference import ReferenceProfileManifestV1
from src.vespercode.workspace.identity_win32 import (
    WorkspaceIdentityV1,
    WorkspaceObjectRejectedV1,
    WorkspaceObjectRejectionCodeV1,
)
from src.vespercode.workspace.object_win32 import (
    FinalObjectIdentityV1,
    WorkspaceObjectKindV1,
    inspect_workspace_object,
)

PathAuthorizationErrorCodeV1 = (
    WorkspaceObjectRejectionCodeV1
    | Literal[
        # Task 9.D authorization decisions (Task 9.A object rejections,
        # including root-resolution codes, propagate unchanged).
        "WORKSPACE_OBJECT_WRONG_KIND",
        "PATH_EXISTS",
        "PATH_PARENT_NOT_FOUND",
        "PATH_PARENT_NOT_DIRECTORY",
        "PATH_SENSITIVE",
        "PROTECTED_ARTIFACT_CHANGED",
        "PATCH_PATH_NOT_EDITABLE",
        "PATH_IGNORED",
        "TREE_INTEGRITY_FAILED",
    ]
)

_SENSITIVE_SEGMENTS: Final = frozenset(
    {".git", ".ssh", ".aws", ".azure", ".gnupg", ".kube"}
)
_SENSITIVE_FILE_NAMES: Final = frozenset({"id_rsa", "id_ed25519", "credentials.json"})
_SENSITIVE_EXTENSIONS: Final = frozenset({".pem", ".key", ".p12", ".pfx"})
_PROTECTED_ROOT_FILES: Final = frozenset(
    {
        "pyproject.toml",
        "requirements.lock",
        "pytest.ini",
        "tox.ini",
        "setup.cfg",
        "mypy.ini",
        ".ruff.toml",
        "ruff.toml",
        "poetry.lock",
        "uv.lock",
        "pdm.lock",
    }
)
_PROTECTED_ANY_LEVEL_FILES: Final = frozenset(
    {"conftest.py", "sitecustomize.py", "usercustomize.py"}
)
_PROTECTED_ANY_LEVEL_NAMES: Final = frozenset(
    {".gitignore", ".gitattributes", ".gitmodules"}
)


def sensitive_path_rule_id(path: str) -> str | None:
    """The first matching SPEC §1.4.3 sensitive-path rule id, or None.

    Rules: any path segment among the reserved credential/config
    directories; a ``.env`` or ``.env.*`` filename; common private-key
    and credential filenames or extensions; ``secrets.*`` prefixes.
    Comparison is Windows case-insensitive for the reserved names.
    """
    segments = path.split("/")
    for segment in segments:
        if segment.casefold() in _SENSITIVE_SEGMENTS:
            return "SENSITIVE_SEGMENT"
    basename = segments[-1].casefold()
    if basename == ".env":
        return "SENSITIVE_DOTENV"
    if basename.startswith(".env."):
        return "SENSITIVE_DOTENV_PREFIX"
    if basename in _SENSITIVE_FILE_NAMES:
        return "SENSITIVE_CREDENTIAL_NAME"
    if basename.startswith("secrets."):
        return "SENSITIVE_SECRETS_PREFIX"
    for extension in _SENSITIVE_EXTENSIONS:
        if basename.endswith(extension):
            return "SENSITIVE_CREDENTIAL_EXTENSION"
    return None


def protected_artifact_path(path: str) -> bool:
    """True when the path is protected by the SPEC §1.4.2 table.

    Protected sets: everything under ``tests/**``; the root project
    configuration and lock files; any-level ``conftest.py``,
    ``sitecustomize.py``, ``usercustomize.py``; any-level
    ``.gitignore``/``.gitattributes``/``.gitmodules``; and root-level
    ``requirements*.txt``.  The table is generated by this single
    versioned function and can never be widened by repository text.
    """
    segments = path.split("/")
    if segments[0] == "tests":
        return True
    if len(segments) == 1:
        if path in _PROTECTED_ROOT_FILES:
            return True
        if fnmatch.fnmatchcase(path, "requirements*.txt"):
            return True
    for segment in segments:
        if segment in _PROTECTED_ANY_LEVEL_FILES:
            return True
        if segment in _PROTECTED_ANY_LEVEL_NAMES:
            return True
    return False


class IgnoreRuleV1(BaseModel):
    """One frozen gitignore rule (SPEC §4.1 frozen ignore rules).

    The rule records its source (a ``.gitignore`` file or
    ``.git/info/exclude``), the base directory the pattern is relative
    to (``""`` is the repository root), the raw pattern (leading ``!``
    and trailing ``/`` already stripped into the closed flags), and the
    negation/directory-only facts.  The aggregate digest binds the whole
    ordered rule set.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)
    schema_version: Literal[1]
    source: Literal["GITIGNORE", "INFO_EXCLUDE"]
    base_directory: StrictStr
    pattern: StrictStr
    negated: StrictBool
    directory_only: StrictBool

    @field_validator("schema_version", mode="before")
    @classmethod
    def _schema_version_is_exact_int(cls, value: object) -> object:
        if not isinstance(value, int) or isinstance(value, bool):
            raise ValueError("schema_version must be the decimal integer 1")
        return value


def _rule_encoding(rule: IgnoreRuleV1) -> str:
    """One canonical line encoding every exact rule field."""
    return (
        f"{rule.source}|{rule.base_directory}|{rule.pattern}|"
        f"{int(rule.negated)}|{int(rule.directory_only)}"
    )


def ignore_rules_digest(rules: tuple[IgnoreRuleV1, ...]) -> str:
    """The sealed SHA-256 identity of the ordered frozen ignore rules."""
    hasher = hashlib.sha256()
    for rule in rules:
        hasher.update(_rule_encoding(rule).encode("utf-8"))
        hasher.update(b"\n")
    return hasher.hexdigest()


class SealedGitFactsV1(Protocol):
    """The sealed Git/ignore facts PathGuard consumes (structural).

    ``GitPreflightResultV1`` (Task 9.C) satisfies this protocol; the
    protocol keeps the dependency one-directional (git_preflight imports
    the rule vocabulary from this module, never the reverse).
    """

    ignore_rules: tuple[IgnoreRuleV1, ...]
    ignore_rules_digest: str
    repository_policy_digest: str


ObjectInspectionPortV1 = Callable[
    [WorkspaceIdentityV1, CanonicalRelativePathV1], FinalObjectIdentityV1
]
"""One 9.A object inspection: sealed identity or closed rejection.

The production binding is ``inspect_workspace_object``; offline tests
inject a deterministic fake port (GREEN-4 boundary).
"""


def _segment_regex(segment: str) -> re.Pattern[str]:
    """Translate one gitignore segment to an anchored full-match regex."""
    return re.compile(fnmatch.translate(segment))


def _match_segments(pattern: str, segments: tuple[str, ...]) -> bool:
    """Match a gitignore pattern against path segments (``**`` aware).

    A single ``**`` part matches zero or more whole segments between the
    literal left and right parts (``a/**/b`` matches ``a/b`` and
    ``a/x/b``).  A pattern containing more than one ``**`` uses syntax
    this matcher cannot prove; it conservatively matches everything so
    the CREATE gate can never fail open on an unprovable rule.
    """
    parts = pattern.split("/")
    if "**" in parts:
        if parts.count("**") > 1:
            return True
        index = parts.index("**")
        left, right = parts[:index], parts[index + 1 :]
        if len(segments) < len(left) + len(right):
            return False
        if not _match_sequence(left, segments[: len(left)]):
            return False
        return _match_sequence(right, segments[len(segments) - len(right) :])
    return _match_sequence(parts, segments)


def _match_sequence(parts: list[str], segments: tuple[str, ...]) -> bool:
    if len(parts) != len(segments):
        return False
    return all(
        _segment_regex(part).fullmatch(segment) is not None
        for part, segment in zip(parts, segments)
    )


def _rule_matches(rule: IgnoreRuleV1, path: str) -> bool:
    """Git-style matching of one rule against one canonical relative path.

    Follows git's ancestor rule: the pattern matches the path when it
    matches the path itself or any ancestor directory (a directory match
    ignores its whole subtree).  A leading ``/`` anchors the pattern to
    the rule's base directory; a slash-less pattern matches the basename
    of any level; a directory-only pattern narrows the same matching to
    directories.  Unprovable syntax (a second ``**``) matches
    conservatively so the CREATE gate never fails open.
    """
    base = rule.base_directory
    relative = path
    if base:
        if not path.startswith(base + "/"):
            return False
        relative = path[len(base) + 1 :]
    segments = tuple(relative.split("/"))
    anchored = rule.pattern.startswith("/")
    pattern = rule.pattern[1:] if anchored else rule.pattern
    if anchored:
        # The anchored pattern matches the object at the base level and
        # (when the object is a directory) everything under it.
        return relative == pattern or relative.startswith(pattern + "/")
    for count in range(1, len(segments) + 1):
        prefix = segments[:count]
        if "/" not in pattern:
            # A slash-less pattern matches the basename at any level
            # (a directory basename match ignores the subtree).
            if _segment_regex(pattern).fullmatch(prefix[-1]) is not None:
                return True
        elif _match_segments(pattern, prefix):
            return True
    return False


def path_is_ignored(rules: tuple[IgnoreRuleV1, ...], path: str) -> bool:
    """True when the last matching frozen rule ignores the path.

    Follows gitignore semantics: the last matching rule wins, so a later
    negation rule re-includes an earlier ignored path.
    """
    ignored = False
    for rule in rules:
        if _rule_matches(rule, path):
            ignored = not rule.negated
    return ignored


def _policy_binding_mismatch(
    git_facts: SealedGitFactsV1, reference: ReferenceProfileManifestV1
) -> bool:
    return git_facts.repository_policy_digest != reference.editable_path_policy.digest


class AuthorizedObjectHandleV1(BaseModel):
    """One closed existing-object authorization: AUTHORIZED or REJECTED.

    An AUTHORIZED handle carries the sealed final-object identity; a
    REJECTED handle carries the stable error code and never any object.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)
    schema_version: Literal[1]
    kind: Literal["AUTHORIZED", "REJECTED"]
    error_code: PathAuthorizationErrorCodeV1 | None = None
    authorized_object: FinalObjectIdentityV1 | None = None

    @field_validator("schema_version", mode="before")
    @classmethod
    def _schema_version_is_exact_int(cls, value: object) -> object:
        if not isinstance(value, int) or isinstance(value, bool):
            raise ValueError("schema_version must be the decimal integer 1")
        return value

    @model_validator(mode="after")
    def _require_exact_outcome(self) -> AuthorizedObjectHandleV1:
        if self.kind == "AUTHORIZED":
            if self.error_code is not None or self.authorized_object is None:
                raise ValueError(
                    "AUTHORIZED results require the sealed object and no error"
                )
        elif self.error_code is None or self.authorized_object is not None:
            raise ValueError("REJECTED results require the error code and no object")
        return self


class AuthorizedParentHandleV1(BaseModel):
    """One closed CREATE authorization: AUTHORIZED or REJECTED.

    An AUTHORIZED handle carries the deepest proven parent identity; a
    REJECTED handle carries the stable error code and never any parent.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)
    schema_version: Literal[1]
    kind: Literal["AUTHORIZED", "REJECTED"]
    error_code: PathAuthorizationErrorCodeV1 | None = None
    authorized_parent: FinalObjectIdentityV1 | None = None

    @field_validator("schema_version", mode="before")
    @classmethod
    def _schema_version_is_exact_int(cls, value: object) -> object:
        if not isinstance(value, int) or isinstance(value, bool):
            raise ValueError("schema_version must be the decimal integer 1")
        return value

    @model_validator(mode="after")
    def _require_exact_outcome(self) -> AuthorizedParentHandleV1:
        if self.kind == "AUTHORIZED":
            if self.error_code is not None or self.authorized_parent is None:
                raise ValueError(
                    "AUTHORIZED results require the sealed parent and no error"
                )
        elif self.error_code is None or self.authorized_parent is not None:
            raise ValueError("REJECTED results require the error code and no parent")
        return self


@dataclass(frozen=True)
class PathGuard:
    """One handle-bound authorization guard over frozen facts only.

    ``git_facts`` carries the sealed Git/ignore observations (9.C),
    ``reference`` carries the frozen editable policy (6.A), and
    ``inspector`` is the 9.A object observation port (production binding:
    real Win32 handles).  Authorization facts and handles only: no
    workspace mutation, patch parsing, policy widening, or string-only
    authorization can exist here.
    """

    git_facts: SealedGitFactsV1
    reference: ReferenceProfileManifestV1
    inspector: ObjectInspectionPortV1 = field(
        default_factory=lambda: inspect_workspace_object
    )

    def __post_init__(self) -> None:
        if self.git_facts.ignore_rules_digest != ignore_rules_digest(
            self.git_facts.ignore_rules
        ):
            raise ValueError("sealed ignore facts do not match their digest")

    def authorize_existing(
        self,
        root: WorkspaceIdentityV1,
        path: CanonicalRelativePathV1,
        expected_kind: WorkspaceObjectKindV1,
    ) -> AuthorizedObjectHandleV1:
        """Authorize one existing object for REPLACE when all facts match.

        Order follows SPEC §4.3: Task 9.A object rejections (including
        aliases) propagate unchanged, then sensitive-path, protected-
        artifact, and editable-policy facts decide.  The returned sealed
        identity is re-verified against the root facts (volume, ancestry,
        kind, reparse, link, ADS, ACL) before it can authorize.
        """
        if _policy_binding_mismatch(self.git_facts, self.reference):
            return _rejected_object("TREE_INTEGRITY_FAILED")
        try:
            identity = self.inspector(root, path)
        except WorkspaceObjectRejectedV1 as error:
            return _rejected_object(error.error_code)
        fact_error = _verify_object_facts(identity, root, expected_kind)
        if fact_error is not None:
            return _rejected_object(fact_error)
        sensitive = sensitive_path_rule_id(path.value)
        if sensitive is not None:
            return _rejected_object("PATH_SENSITIVE")
        if protected_artifact_path(path.value):
            return _rejected_object("PROTECTED_ARTIFACT_CHANGED")
        if not self.reference.editable_path_policy.matches(path, "REPLACE"):
            return _rejected_object("PATCH_PATH_NOT_EDITABLE")
        return AuthorizedObjectHandleV1(
            schema_version=1, kind="AUTHORIZED", authorized_object=identity
        )

    def authorize_create(
        self, root: WorkspaceIdentityV1, path: CanonicalRelativePathV1
    ) -> AuthorizedParentHandleV1:
        """Authorize one CREATE parent when every fact family matches.

        An exact existing object rejects with ``PATH_EXISTS``; a case or
        Unicode alias of an existing object rejects with
        ``PATH_ALIAS_COLLISION`` (the Task 9.A observation port proves
        the alias from the final path); every ancestor must be a proven
        directory under the root; the new path must be non-sensitive,
        non-protected, editable, and non-ignored under the sealed ignore
        rules.
        """
        if _policy_binding_mismatch(self.git_facts, self.reference):
            return _rejected_parent("TREE_INTEGRITY_FAILED")
        try:
            self.inspector(root, path)
        except WorkspaceObjectRejectedV1 as error:
            if error.error_code != "WORKSPACE_OBJECT_NOT_FOUND":
                return _rejected_parent(error.error_code)
        else:
            return _rejected_parent("PATH_EXISTS")
        sensitive = sensitive_path_rule_id(path.value)
        if sensitive is not None:
            return _rejected_parent("PATH_SENSITIVE")
        if protected_artifact_path(path.value):
            return _rejected_parent("PROTECTED_ARTIFACT_CHANGED")
        if not self.reference.editable_path_policy.matches(path, "CREATE"):
            return _rejected_parent("PATCH_PATH_NOT_EDITABLE")
        if path_is_ignored(self.git_facts.ignore_rules, path.value):
            return _rejected_parent("PATH_IGNORED")
        parent, parent_error = self._prove_parent_chain(root, path)
        if parent_error is not None:
            return _rejected_parent(parent_error)
        if parent is None:
            # No provable parent.  With the frozen built-in editable
            # policy this branch is structurally unreachable — a CREATE
            # must start with ``src/`` and therefore has at least one
            # ancestor — but the closed rejection is the correct
            # fail-closed outcome for any future policy shape; it is
            # never an assertion.
            return _rejected_parent("PATH_PARENT_NOT_FOUND")
        return AuthorizedParentHandleV1(
            schema_version=1, kind="AUTHORIZED", authorized_parent=parent
        )

    def _prove_parent_chain(
        self, root: WorkspaceIdentityV1, path: CanonicalRelativePathV1
    ) -> tuple[FinalObjectIdentityV1 | None, PathAuthorizationErrorCodeV1 | None]:
        """Prove every ancestor directory under the root.

        Returns the deepest proven parent identity and None, or None and
        the stable closed error for the first unprovable link
        (``PATH_PARENT_NOT_FOUND`` for a missing ancestor,
        ``PATH_PARENT_NOT_DIRECTORY`` for a non-directory ancestor, or
        the propagated 9.A fact rejection).
        """
        segments = path.value.split("/")
        proven: FinalObjectIdentityV1 | None = None
        for count in range(1, len(segments)):
            parent_path = CanonicalRelativePathV1("/".join(segments[:count]))
            try:
                identity = self.inspector(root, parent_path)
            except WorkspaceObjectRejectedV1 as error:
                if error.error_code == "WORKSPACE_OBJECT_NOT_FOUND":
                    return None, "PATH_PARENT_NOT_FOUND"
                return None, error.error_code
            fact_error = _verify_object_facts(identity, root, "DIRECTORY")
            if fact_error is not None:
                if fact_error == "WORKSPACE_OBJECT_WRONG_KIND":
                    return None, "PATH_PARENT_NOT_DIRECTORY"
                return None, fact_error
            proven = identity
        return proven, None


def _rejected_object(
    error_code: PathAuthorizationErrorCodeV1,
) -> AuthorizedObjectHandleV1:
    return AuthorizedObjectHandleV1(
        schema_version=1, kind="REJECTED", error_code=error_code
    )


def _rejected_parent(
    error_code: PathAuthorizationErrorCodeV1,
) -> AuthorizedParentHandleV1:
    return AuthorizedParentHandleV1(
        schema_version=1, kind="REJECTED", error_code=error_code
    )


def _verify_object_facts(
    identity: FinalObjectIdentityV1,
    root: WorkspaceIdentityV1,
    expected_kind: WorkspaceObjectKindV1,
) -> PathAuthorizationErrorCodeV1 | None:
    """Re-verify the sealed object facts against the root; None when all
    facts match, else the stable closed error code."""
    if identity.volume_serial_number != root.volume_serial_number:
        return "WORKSPACE_OBJECT_VOLUME_MISMATCH"
    try:
        common = os.path.commonpath(
            [
                os.path.normcase(identity.final_absolute_path),
                os.path.normcase(root.canonical_absolute_path),
            ]
        )
    except ValueError:
        return "PATH_OUTSIDE_WORKSPACE"
    if common != os.path.normcase(root.canonical_absolute_path):
        return "PATH_OUTSIDE_WORKSPACE"
    if identity.object_kind != expected_kind:
        return "WORKSPACE_OBJECT_WRONG_KIND"
    if identity.reparse_tag != 0 or (
        identity.object_kind == "FILE" and identity.link_count != 1
    ):
        return "UNSUPPORTED_WORKSPACE_OBJECT"
    if identity.has_alternate_data_streams:
        return "UNSUPPORTED_WORKSPACE_OBJECT"
    if not identity.acl_observable:
        return "WORKSPACE_OBJECT_ACL_UNPROVEN"
    return None
